#!/bin/sh

set -eu

for venv in 'venv' 'venv3'; do
    "./$venv/bin/py.test" --doctest-modules \
        salt/tls-terminator/test.py \
        salt/hardening/test_print_dependent_modules.py "$@" \
        salt/sentry-forwarder/test_forwarder.py \
        salt/dotfiles/test_dotfiles.py \
        extensions/pillar/test_* \
        salt/_modules/test_* \
        salt/_states/test_* \
        "$@"
done
