#!/bin/bash

# Cronic v2 - cron job report wrapper
# Copyright 2007 Chuck Houpt. No rights reserved, whatsoever.
# Public Domain CC0: http://creativecommons.org/publicdomain/zero/1.0/
# Modified by thusoy to use mktemp for safer temporary file creation and
# to ignore trace handling

# This script exist to enable scripts to print debug data to stdout and errors
# to stderr without resulting in a cron email for the presence of data in
# stdout. Only stderr or exit code != 0 triggers output from this script.

set -eu

OUT=$(mktemp /tmp/cronic.out.XXXXXXXX)
ERR=$(mktemp /tmp/cronic.err.XXXXXXXX)

set +e
"$@" >$OUT 2>$ERR
RESULT=$?
set -e

if [ $RESULT -ne 0 -o -s "$ERR" ]; then
    echo "Cronic detected failure or error output for the command:"
    echo "$@"
    echo
    echo "RESULT CODE: $RESULT"
    echo
    echo "ERROR OUTPUT:"
    cat "$ERR"
    echo
    echo "STANDARD OUTPUT:"
    cat "$OUT"
fi

rm -f "$OUT" "$ERR"
